I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/evts_generaux/rien.rpy", line 91, in script
    $ LancerEvtVide(situation_)
  File "game/evts_generaux/rien.rpy", line 91, in <module>
    $ LancerEvtVide(situation_)
  File "game/evts_generaux/rien.rpy", line 66, in LancerEvtVide
    renpy.show(random.choice(scenesParDefaut))
IndexError: list index out of range

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/evts_generaux/rien.rpy", line 91, in script
    $ LancerEvtVide(situation_)
  File "renpy/ast.py", line 928, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2245, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/evts_generaux/rien.rpy", line 91, in <module>
    $ LancerEvtVide(situation_)
  File "game/evts_generaux/rien.rpy", line 66, in LancerEvtVide
    renpy.show(random.choice(scenesParDefaut))
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/random.py", line 277, in choice
  File "renpy/python.py", line 992, in __getitem__
    rv = list.__getitem__(self, index)
IndexError: list index out of range

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
extremisLaVille 1.0
Thu May 19 21:30:28 2022
